name: offline_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pip:
    - asgiref==3.8.1
    - blinker==1.9.0
    - click==8.2.0
    - flask==3.1.0
    - importlib-metadata==8.7.0
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - python-dotenv==1.1.0
    - werkzeug==3.1.3
